### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by prrockzed** [prrockzed/chessed#2]
**Describe the bug**
The project, **Chessed**, isn't responsive. While it displays correctly on laptops and similar-sized screens, it doesn't render properly on phones or smaller devices.

**To Reproduce**
1. Open the project on your phone.
2. Alternatively, use the Inspect option in your browser and switch to a mobile view (e.g., using device emulation).

**Expected behavior**
The project should display correctly across all screen sizes, ensuring a smooth and responsive user experience on phones, tablets, and desktops.

**Screenshots**

![Screenshot 2024-11-16 at 3 48 02 PM](https://github.com/user-attachments/assets/9ea9de0c-3bec-48b1-a997-6fc96a194371)
![Screenshot 2024-11-16 at 3 47 54 PM](https://github.com/user-attachments/assets/66f28356-f004-4abc-80db-e79e47643baa)

**Additional context**
This issue likely stems from CSS layout or media query problems. Updating the CSS to handle responsiveness should resolve the issue. This is not a logical bug but a visual/display problem.

**Comment by ThePhoenix08** [comment]
Hi [Project Owner's Name],

I’d love to work on making the app responsive. Here’s my proposed plan:

1. **Dynamic Tile Size:**
   - Replace the fixed `50px` tile size with a dynamic approach using CSS variables defined in `:root`.
   - Make other metrics like chess piece size and highlight size dependent on the tile size.
   
```css
/* index.css */
:root {
  /* strictly global css variables only */

  /* size */
  --tile-size: 3rem;
  --chess-piece-size: calc(var(--tile-size) * 0.85);
  --tile-highlight-size: calc(var(--tile-size) * 0.25);
  --tile-highlight-chess-piece-size: calc(var(--tile-size) * 0.9);
}
```
   - Use media query breakpoints to adjust the tile size for different platforms (possibly with `rem` or viewport units).
```css
/* mediaQueries.css */
@media all and (min-width: 768px) {
  /* tablet landscape and desktop styles here */
  :root {
    --tile-size: 3rem;
  }
}

@media all and (min-width: 480px) and (max-width: 768px) {
  /* tablet styles here */
  :root {
    --tile-size: 2.5rem;
  }
}

@media all and (max-width: 480px) {
  /* small phone styles here */
  :root {
    --tile-size: 2rem;
  }
}
```

2. **Player Name Bubble:**
   - Redesign the player name bubble to resolve positioning issues on smaller screens.

3. **Modal Responsiveness:**
   - Fix the modal to work better on smaller screens.
   - Additionally, I noticed that the chess game remains partially playable (via drag-and-drop) even when the modal is open. As this is more of a logic/UI issue than responsiveness, it should be addressed independently of this issue, just pointing it out as I found it while testing.

Let me know if this approach aligns with your vision, and if so, please assign me this issue. Looking forward to contributing! 😊
